---

- name: Check jq binary file
  tags:
    - jq
  ansible.builtin.stat:
    path: "{{ jq_bin_path }}/jq"
  become: false
  register: jq_binary


- name: "Download jq â†’ {{ jq_url }}"
  tags:
    - jq
  ansible.builtin.get_url:
    url: "{{ jq_url }}"
    dest: "{{ jq_bin_path }}/jq"
    timeout: "42"
    owner: "root"
    group: "root"
    mode: "0755"
  when: not jq_binary.stat.exists | bool
